// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewOrder struct {
	Description string         `json:"description"`
	Television  *NewTelevision `json:"television"`
}

type NewTechnician struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type NewTelevision struct {
	Model string `json:"model"`
	Brand string `json:"brand"`
}

type NewUser struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Order struct {
	ID           string      `json:"id"`
	Description  string      `json:"description"`
	Status       string      `json:"status"`
	Calification *int        `json:"calification"`
	Feedback     *string     `json:"feedback"`
	URL          *string     `json:"url"`
	User         *User       `json:"user"`
	Technician   *Technician `json:"technician"`
	Tv           *Television `json:"tv"`
}

type OrderCreated struct {
	Token string `json:"token"`
	URL   string `json:"url"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Technician struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Television struct {
	ID    string `json:"id"`
	Model string `json:"model"`
	Brand string `json:"brand"`
}

type User struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
